apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: default
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: 'selenium-hub'
        static_configs:
          - targets: ['selenium-hub-export-service:9104']

      - job_name: 'prometheus'
        static_configs:
          - targets: ['prometheus-service:9090']

  custom.rules: |
    groups:
      - name: custom.rules
        rules:
          - record: free_nodes_percentage
            expr: 100 * (selenium_grid_node_count - selenium_grid_session_count) / selenium_grid_node_count
