apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: custom-metrics-reader
rules:
- apiGroups:
  - custom.metrics.k8s.io
  resources:
  - "*"
  verbs:
  - get
  - list
  - watch
---
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1beta1.custom.metrics.k8s.io
spec:
  service:
    name: custom-metrics-apiserver
    namespace: default
  group: custom.metrics.k8s.io
  version: v1beta1
  insecureSkipTLSVerify: true
  groupPriorityMinimum: 100
  versionPriority: 100
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: custom-metrics-reader-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: custom-metrics-reader
subjects:
- kind: User
  name: gke_level-climber-382119_europe-central2_fb-poster-cluster
