---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db
          image: postgres
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DB
              value: postgres
          ports:
            - containerPort: 5432
          resources:
            limits:
              cpu: 500m
              memory: 2Gi
            requests:
               memory: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: user
            - name: RABBITMQ_DEFAULT_PASS
              value: password
          ports:
            - containerPort: 5672
            - containerPort: 15672
          resources:
            limits:
              cpu: 500m
              memory: 2Gi
            requests:
               memory: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fb-poster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fb-poster
  template:
    metadata:
      labels:
        app: fb-poster
    spec:
      containers:
        - name: fb-poster
          image: gcr.io/level-climber-382119/fb-poster:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: bot-secret
                  key: secret-key
            - name: ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: bot-secret
                  key: access-key
            - name: HOST_IP
              value: "http://34.116.171.18:30002/"
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 500m
              memory: 2Gi
            requests:
               memory: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: firefox
spec:
  selector:
    matchLabels:
      app: firefox
  replicas: 1
  template:
    metadata:
      labels:
        app: firefox
    spec:
      containers:
        - name: firefox
          image: selenium/node-firefox:dev
          imagePullPolicy: IfNotPresent
          env:
            - name: SE_EVENT_BUS_HOST
              value: selenium-hub-service
            - name: SE_EVENT_BUS_PUBLISH_PORT
              value: "4442"
            - name: SE_EVENT_BUS_SUBSCRIBE_PORT
              value: "4443"
          resources:
            limits:
              cpu: 500m
              memory: 2Gi
            requests:
               memory: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-hub
spec:
  selector:
    matchLabels:
      app: selenium-hub
  replicas: 1
  template:
    metadata:
      labels:
        app: selenium-hub
    spec:
      containers:
        - name: selenium-hub
          image: selenium/hub
          imagePullPolicy: IfNotPresent
          env:
            - name: GRID_BROWSER_TIMEOUT
              value: "120000"
            - name: GRID_TIMEOUT
              value: "120000"
            - name: GRID_NEW_SESSION_WAIT_TIMEOUT
              value: "120000"
          ports:
            - containerPort: 4442
            - containerPort: 4443
            - containerPort: 4444
          resources:
            limits:
              cpu: 500m
              memory: 2Gi
            requests:
               memory: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: fb-poster-service
spec:
  selector:
    app: fb-poster
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30002

---
apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  selector:
    app: db
  ports:
    - name: db
      port: 5432
      targetPort: 5432
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
spec:
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
    - name: management
      port: 15672
      targetPort: 15672
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: selenium-hub-service
spec:
  selector:
    app: selenium-hub
  ports:
    - name: hub-port
      port: 4444
      targetPort: 4444
    - name: publish-port
      port: 4442
      targetPort: 4442
    - name: subscribe-port
      port: 4443
      targetPort: 4443
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: firefox-service
spec:
  selector:
    app: firefox
  ports:
    - name: firefox-port
      port: 5900
      targetPort: 5900
  type: ClusterIP
