apiVersion: batch/v1
kind: CronJob
metadata:
  name: task-executer-cronjob
spec:
  schedule: "0 */3 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: task-executer
            image: gcr.io/stellar-aleph-398117/cron-task-executer
            resources:
              requests:
                memory: 500Mi
              limits:
                cpu: 1000m
                memory: 4Gi
          restartPolicy: OnFailure

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: task-status-reset-cronjob
spec:
  schedule: "50 23 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: task-status-reset
            image: gcr.io/stellar-aleph-398117/cron-task-status-reset
            resources:
              requests:
                cpu: "100m"
                memory: "200Mi"
              limits:
                cpu: "200m"
                memory: "400Mi"
          restartPolicy: OnFailure
