apiVersion: batch/v1
kind: CronJob
metadata:
  name: task-executer-cronjob
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: task-executer
            image: gcr.io/stellar-aleph-398117/cron-task-executer
            env:
              - name: URL
                value: "http://34.116.171.18/"
              - name: GOOGLE_APPLICATION_CREDENTIALS
                value: "/var/secrets/google/key.json"
            volumeMounts:
              - name: google-cloud-key
                mountPath: /var/secrets/google
            resources:
              requests:
                memory: "500Mi"
                cpu: "1000m"
              limits:
                memory: "4Gi"
                cpu: "1000m"
          volumes:
          - name: google-cloud-key
            secret:
              secretName: iam-storage

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: task-status-reset-cronjob
spec:
  schedule: "50 23 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: task-status-reset
            image: gcr.io/stellar-aleph-398117/cron-task-status-reset
            env:
              - name: GOOGLE_APPLICATION_CREDENTIALS
                value: "/var/secrets/google/key.json"
            volumeMounts:
              - name: google-cloud-key
                mountPath: /var/secrets/google
            resources:
              requests:
                cpu: "100m"
                memory: "200Mi"
              limits:
                cpu: "200m"
                memory: "400Mi"
          volumes:
          - name: google-cloud-key
            secret:
              secretName: iam-storage
