---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fb-poster-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fb-poster-api
  template:
    metadata:
      labels:
        app: fb-poster-api
    spec:
      initContainers:
        - name: init-get-ip
          image: gcr.io/stellar-aleph-398117/init-script
          volumeMounts:
          - name: temp-volume
            mountPath: /tmp
      containers:
        - name: fb-poster-api
          image: gcr.io/stellar-aleph-398117/fb-poster:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: google-cloud-key
              mountPath: /var/secrets/google
            - name: user-secrets
              mountPath: /etc/user-secrets
              readOnly: true
            - name: db-secrets
              mountPath: /etc/db-secrets
              readOnly: true
            - name: temp-volume
              mountPath: /tmp
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 1000m
              memory: 4Gi
            requests:
              memory: 2Gi
      volumes:
        - name: google-cloud-key
          secret:
            secretName: iam-storage
        - name: user-secrets
          secret:
            secretName: user-secrets
        - name: db-secrets
          secret:
            secretName: db-secrets
        - name: temp-volume
          emptyDir: { }