apiVersion: v1
kind: Service
metadata:
  name: selenium-hub-service
spec:
  selector:
    app: selenium-hub
  ports:
    - name: hub-port
      port: 4444
      targetPort: 4444
    - name: publish-port
      port: 4442
      targetPort: 4442
    - name: subscribe-port
      port: 4443
      targetPort: 4443
  type: ClusterIP