FROM python:3.9

WORKDIR /code

COPY ../requirements.txt /code/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

COPY ./cron_jobs/task_executer.py /code/task_executer.py

ENV PYTHONPATH=/code

CMD ["python", "task_executer.py"]
