FROM python:3.9

WORKDIR /code

COPY ../requirements.txt /code/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

COPY ./cron_jobs/task_status_reset.py /code/cron_jobs/task_status_reset.py
COPY ./agents/logger.py /code/agents/logger.py

ENV PYTHONPATH=/code

CMD ["python", "/code/cron_jobs/task_status_reset.py"]
